title: "Scala Spores | Making Distributed Programming More Functional"

githuburl: "http://github.com/scala/spores"
projecttitle: "Scala Spores"
projecttagline: "Making Distributed Programming More Functional"

baseurl: ""