title: "Spores | Making Distributed Programming More Functional"

githuburl: "http://github.com/scala/spores"
projecttitle: "Spores"
projecttagline: "Making Distributed Programming More Functional"

baseurl: ""